title: candace woodbury
description: essays and short stories from someone who'd rather be outside.
url: "https://candacewoodbury.com"
baseurl: ""

author:
  name: candace woodbury
  email: hello@candacewoodbury.com

google_analytics: G-SC80GDW5EE

markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

navigation:
  - title: essays
    url: /essays/
  - title: short stories
    url: /short-stories/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .jekyll-cache
  - .htaccess